# Generated by Django 4.2.19 on 2025-02-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
